src/components/Web/SideBar/SideBar.stories.tsx
src/components/Web/SideBar/SideBar.tsx

add:サイドバーの追加 #2

---

src/components/Header/Header.stories.tsx
src/components/Header/Header.tsx

add:ヘッダー追加 #1

---

src/components/Web/TopScroll/TopScroll.stories.tsx
src/components/Web/TopScroll/TopScroll.tsx
src/types/web.ts

add:トップ画面の各部門にジャンプするボタンの実装 #43

---

package.json
pnpm-lock.yaml
src/components/Common/Date/Date.stories.tsx
src/components/Common/Date/Date.tsx

add:日付用コンポーネントの作成 #29

---

.storybook/preview.tsx

add:storybookをダークモードに対応 #53

---

src/pages/web/artifact/[category]/[artifactId].tsx
src/pages/web/artifact/[category]/index.tsx
src/pages/web/artifact/index.tsx

add: 動的ルーティングの作成 #57

---

_templates/generator/new/component.tsx.t

fix:hygenライブラリ使用における軽微な修正 #49

---

src/components/Web/User/UserCard.stories.tsx
src/components/Web/User/UserCard.tsx

add:ユーザーカードのオプションを追加 #54

---

src/components/Common/Date/Date.tsx
src/components/Web/Artifact/Artifact.stories.tsx
src/components/Web/Artifact/Artifact.tsx
src/libs/getCategory.ts

add:作品表示カードの作成 #23

---

src/components/Common/FooterIcons/FooterIcons.stories.tsx
src/components/Common/FooterIcons/FooterIcons.tsx
src/types/web.ts

add:フッターアイコンを追加 #31

---

src/components/Common/TopLoading/TopLoading.tsx
src/components/Common/othres/Layout.tsx

fix:一般通過C3ちゃんの修正 #69

---

src/libs/theme.tsx

add:textの色を追加 #72

---

src/components/Web/RedirectMap/RedirectMap.stories.tsx
src/components/Web/RedirectMap/RedirectMap.tsx

add:/mapに遷移するコンポーネントの作成 #15

---

src/pages/web/artifact/[category]/index.tsx

add:各カテゴリのページの作成 #71

---

src/components/Web/CategoryOutlineCard/CategoryOutlineCard.stories.tsx
src/components/Web/CategoryOutlineCard/CategoryOutlineCard.tsx
src/types/web.ts

add:カテゴリ説明コンポーネントの追加 #73

---

package.json
pnpm-lock.yaml
src/components/Web/Favorite/Favorite.stories.tsx
src/components/Web/Favorite/Favorite.tsx
src/hooks/common.ts

add:いいねボタンの追加 #21

---

src/components/Web/FlowBackImages/FlowBackImages.stories.tsx
src/components/Web/FlowBackImages/FlowBackImages.tsx
src/constants/flowImages.ts

add:画像が流れる背景コンポーネントの作成 #95

---

src/components/Web/TopBackground/TopBackground.stories.tsx
src/components/Web/TopBackground/TopBackground.tsx
src/constants/topBackground.ts
src/types/web.ts

add:トップページのタイトル背景画像の作成 #108

---

src/pages/web/artifact/[category]/[artifactId].tsx

fix:背景画像のレイアウト修正 #111

---

src/components/Common/Date/Date.tsx

fix:表示時間をマイナス9時間 #132
